### ISSUE TITLE
Setup test site for DCCEEW to test the new data source integration

### ISSUE THREAD

**Issue by t83714** [magda-io/magda-config-data.gov.au#45]
Our plan will be:
- Remove old CSW connection & all datasets associate with it
- Install ArcGIS hub connection at endpoint: https://fed.dcceew.gov.au/api/feed/dcat-us/1.1.json
- Datatsets manually curated via DCCEEW’s data.gov.au account via CKAN UI will be left as they are

We will create a test site on dev cluster with relevant data sources and test the changes (e.g. data removal & new data source etc).
Once the test is done, I will share with DCCEEW and they can check test site to verify the metadata mapping (which can be config via ArcGiS hub config)

**Comment by AnaBelgun** [comment]
Update 14 Aug 23: 
- the freeze bug is due to support of Esri Feature Service tiles not being fully supported in Terria

**Comment by t83714** [comment]
Test site: https://dcceew.dev.magda.io/ has been shared with DCCEEW.
Plan to deploy the changes this Friday 5:00PM
